# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

file_format: "1"
id: 9ptimus
name: 9ptimus
type: shield
requires: [../seeeduino_xiao_ble.overlay, seeeduino_xiao_ble]
features:
  - keys
siblings:
  - 9ptimus_left
  - 9ptimus_right
