# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

file_format: "1"
id: fsweed
name: fsweed
type: shield
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - fsweed_left
  - fsweed_right
