manifest:
  remotes:
    - name: zmkfirmware
      # url-base: https://github.com/zmkfirmware
      # url-base: https://github.com/infused-kim/zmk-zephyr/commits/v2.5.0%2Bzmk-fixes%2Bkim-fixes 
      url-base: https://github.com/petejohanson
  # projects:
  #   - name: zmk
  #     remote: zmkfirmware
  #     revision: main
  #     import: app/west.yml
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: power/domains-and-device-runtime
      import: app/west.yml
  self:
    path: config
